# Generated by Django 5.1.3 on 2024-11-23 10:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userimports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimports',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='userimports',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
