# Generated by Django 5.1.3 on 2024-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userimports_content_alter_userimports_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimports',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
