# Generated by Django 5.1.3 on 2024-11-28 13:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userimports_is_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimports',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[accounts.models.validate_file_extension]),
        ),
    ]
