# Generated by Django 5.1.3 on 2024-11-28 13:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userimports_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimports',
            name='content2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='content'),
        ),
    ]
