# Generated by Django 5.1.3 on 2024-12-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='pub_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
